name: Python CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the code from the repository
            - name: Check out code
              uses: actions/checkout@v2
            
            # Step 2: Setup python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            
            # Step 3: Install Dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            # Step 4: Run the tests
            - name: Run tests
              run: pytest
